[platformio]
default_envs = xiao_esp32s3_header

[env]
platform = https://github.com/pioarduino/platform-espressif32.git#54.03.21
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
platform_packages =
  tool-esptoolpy @ platformio/tool-esptoolpy@1.40801.0
extra_scripts =
  pre:tools/esptool_compat.py
  post:tools/esptool_compat.py
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DOLED_I2C_ADDRESS=0x3C
  -DBUTTON_EXPANDER_ADDRESS=0x20
lib_deps =
  jgromes/RadioLib@7.7.1
  olikraus/U8g2@2.36.18

[env:xiao_esp32s3_header]
build_flags =
  ${env.build_flags}
  -DENABLE_ADS1115_POWER=0

; Select only after fitting the optional ADS1115 and both voltage dividers.
[env:xiao_esp32s3_header_power]
build_flags =
  ${env.build_flags}
  -DENABLE_ADS1115_POWER=1
